### ISSUE TITLE
403 on supervision after 2-3 supervised calls

### ISSUE THREAD

**Issue by nimosunbit** [tylerlong/ringcentral-softphone-demo#2]
Hey,

It seems that after the app is running for a few minutes and took several calls, we receive 403.
Note that I checked it for both inbounds and outbound, while the call has a status `answered`.
```
Error: 403 Forbidden
    at Client.<anonymous> (/usr/src/call-supervision/node_modules/@ringcentral/sdk/src/http/Client.ts:78:37)
    at step (/usr/src/call-supervision/node_modules/@ringcentral/sdk/lib/http/Client.js:56:23)
    at Object.next (/usr/src/call-supervision/node_modules/@ringcentral/sdk/lib/http/Client.js:37:53)
    at fulfilled (/usr/src/call-supervision/node_modules/@ringcentral/sdk/lib/http/Client.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://platform.ringcentral.com/restapi/v1.0/account/~/telephony/sessions/{telephonySessionId}/supervise',
      status: 403,
      statusText: 'Forbidden',
      headers: [Headers]
    }
  },
```

How to reproduce: I changed the code from making supervision upon event to making supervision upon request. 

```
import RingCentral from "@ringcentral/sdk";
import { nonstandard } from "wrtc";
import Softphone from "ringcentral-softphone";
import fs from "fs";

const express = require("express");


const rc = new RingCentral({
  server: process.env.RINGCENTRAL_SERVER_URL,
  clientId: process.env.RINGCENTRAL_CLIENT_ID,
  clientSecret: process.env.RINGCENTRAL_CLIENT_SECRET,
});

(async () => {
  await rc.login({
    username: process.env.RINGCENTRAL_USERNAME,
    extension: process.env.RINGCENTRAL_EXTENSION,
    password: process.env.RINGCENTRAL_PASSWORD,
  });
  const softphone = new Softphone(rc);
  await softphone.register();

  softphone.on("INVITE", (sipMessage) => {
    softphone.answer(sipMessage);
    console.log(sipMessage["headers"]["p-rc-api-ids"]);
    const filename = sipMessage["headers"]["p-rc-api-ids"]
      .split(";")[1]
      .split("=")[1];
    console.log(filename);
    softphone.once("track", (e) => {
      console.log(e);
      console.log("track");
      const audioSink = new nonstandard.RTCAudioSink(e.track);
      //    let speaker = null
      let prevSampleRate = null;
      const audioFilePath = `${filename}.raw`;
      if (fs.existsSync(audioFilePath)) {
        fs.unlinkSync(audioFilePath);
      }
      const writeStream = fs.createWriteStream(audioFilePath, { flags: "a" });
      audioSink.ondata = (data) => {
        writeStream.write(Buffer.from(data.samples.buffer));
      };
      softphone.once("BYE", () => {
        console.log("BYE");
        audioSink.stop();
      });
    });
  });

  const app = express();
  app.use(express.json());

  app.get("/record/:telephonySessionId/:agentExtensionId", async function (req, res) {
    let telephonySessionId = req.params["telephonySessionId"];
    let agentExtensionId = req.params["agentExtensionId"]
    console.log(telephonySessionId)
    
    await rc.post(
      `/restapi/v1.0/account/~/telephony/sessions/${telephonySessionId}/supervise`,
      {
        mode: "Listen",
        supervisorDeviceId: softphone.device.id,
        agentExtensionId: agentExtensionId,
      }
    ).then(
      function(data) {
        console.log(data)
        res.send(JSON.stringify(data))
      }
    ).catch(
      function(e) {
        console.log(e)
        res.send(JSON.stringify(e));
      }
    )
  });

  const PORT = 5050;

  const server = app.listen(PORT, function () {
    console.log(`Running on //:${PORT}`);
  });
})();
```

**Comment by tylerlong** [comment]
It's probably by design. If the call is over when you try to supervise, there will be error.

**Comment by tylerlong** [comment]
To troubleshoot it further, print the response body:

```js
// Print API call errors, if there are any
    rc.client().on(events.requestError, async e => {
      console.log(e);
      console.log(await e.response.json());
    });
```
